### ISSUE TITLE
AttributeError: 'TransformersBasedTagger' object has no attribute '_tokenizer'

### ISSUE THREAD

**Issue by whisere** [heartexlabs/label-studio-transformers#10]
predict run into error:
label-studio-ml-backend/ner-ml-backend/ner.py", line 368, in predict
    predict_set = SpanLabeledTextDataset(texts, tokenizer=self._tokenizer, **self._dataset_params_dict)
AttributeError: 'TransformersBasedTagger' object has no attribute '_tokenizer'

**Comment by whisere** [comment]
and had these on  terminal:
[werkzeug::_log::113] 127.0.0.1 - - [08/Apr/2021 12:48:42] "POST /predict HTTP/1.1" 500 -
[werkzeug::_log::113] 127.0.0.1 - - [08/Apr/2021 12:48:47] "GET /health HTTP/1.1" 200 -
[werkzeug::_log::113] 127.0.0.1 - - [08/Apr/2021 12:48:47] "POST /setup HTTP/1.1" 200 -
[werkzeug::_log::113] 127.0.0.1 - - [08/Apr/2021 12:48:53] "POST /train HTTP/1.1" 400 -

**Comment by whisere** [comment]
This happened when using ner.py and the ner template comes with labelstudio:
```
<View>
  <Labels name="label" toName="text">
    <Label value="PER" background="red"/>
    <Label value="ORG" background="darkorange"/>
    <Label value="LOC" background="orange"/>
    <Label value="MISC" background="green"/>
  </Labels>
  <Text name="text" value="$ner"/>
</View>
```

**Comment by whisere** [comment]
When using the bert_classifier.py and the text classification template in labelstudio, 
` <View>
  <Text name="text" value="$text"/>
  <View style="box-shadow: 2px 2px 5px #999; padding: 20px; margin-top: 2em; border-radius: 5px;">
    <Header value="Choose text sentiment"/>
    <Choices name="sentiment" toName="text" choice="single" showInLine="true">
      <Choice value="Positive"/>
      <Choice value="Negative"/>
      <Choice value="Neutral"/>
    </Choices>
  </View>
</View>`
reported this error:
/bert_classifier.py", line 45, in __init__
    assert self.info['type'] == 'Choices'
AssertionError

**Comment by whisere** [comment]
Or some other templates we should use?

**Comment by 2hanandeh** [comment]
Did you manage to find a solution for this? @whisere @niklub

**Comment by KonstantinKorotaev** [comment]
Hi @2hanandeh 
We have moved transformers to label-studio-ml-backend.
Could you please check fix with docker-compose in [branch](https://github.com/heartexlabs/label-studio-ml-backend/tree/fix/transformers-bert)?

**Comment by wojnarabc** [comment]
Hi @KonstantinKorotaev, unfortunately still the same on my end.
Steps taken:
1. Cloned fix/transformer-bert branch 
2. Initiated ner-ml backend (...examples/ner.py) with success
3. Opened Label Studio and created Named Entity Recognition project
4. Linked my ner-ml backend directly from UI (settings->Machine Learning)
Till this moment all seems to be in order. 

When i start labeling dataset though, i'm getting: 
```
"Traceback (most recent call last):
  File "/Users/user/Projects/label-studio-ml-backend/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/Users/user/Projects/label-studio-ml-backend/label_studio_ml/api.py", line 31, in _predict
    predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
  File "/Users/user/Projects/label-studio-ml-backend/label_studio_ml/model.py", line 277, in predict
    predictions = m.model.predict(tasks, **kwargs)
  File "/Users/user/Projects/label-studio-ml-backend/label_studio_ml/my-ml-backend-ner/ner.py", line 369, in predict
    predict_set = SpanLabeledTextDataset(texts, tokenizer=self._tokenizer, **self._dataset_params_dict)
AttributeError: 'TransformersBasedTagger' object has no attribute '_tokenizer''"
```
each time i drop a label Label Studio.

Any ideas on how to carry on with this one ?

**Comment by FahriBilici** [comment]
I have same problem. Are there any solution?

**Comment by KonstantinKorotaev** [comment]
Hi @FahriBilici and @wojnarabc 
I have fixed the issue in https://github.com/heartexlabs/label-studio-ml-backend
Check ner example

**Comment by wojnarabc** [comment]
Thanks @KonstantinKorotaev, it gives me now "[ERROR] [ner::predict::369] No model loaded! Please train model before getting predictions!" instead. I guess it was about Label Studio requesting predictions by default when ML backend was on. It's much more informative now.
