### ISSUE TITLE
Error with ner.py

### ISSUE THREAD

**Issue by somejonus** [heartexlabs/label-studio-transformers#13]
When using the quick start for BERT NER:
`label-studio-ml init my-ml-backend --script models/ner.py`

This error occurs:
`AttributeError: type object 'BertConfig' has no attribute 'pretrained_config_archive_map'`

**Comment by Luishfs** [comment]
How was that solved?

**Comment by somejonus** [comment]
> How was that solved?

If I remember correctly: take a look into ner.py. There should be a line, one of the first after the import statements, that uses `pretrained_config_archive_map` to create a variable. Simply comment/delete this line, the variable is never used. Hope this helps!

Also, it's fixed in this pull request: #15
