### ISSUE TITLE
How do I know which model is trained for ner?

### ISSUE THREAD

**Issue by zephyrwang** [heartexlabs/label-studio-transformers#17]
In ner model code, there are four model classes. how do i know which model is trained? like Bert or Roberta?

**Comment by makseq** [comment]
@zephyrwang https://github.com/heartexlabs/label-studio-transformers/blob/master/models/ner.py#L458 --- probably it's 'bert', because it's by default here.

**Comment by zephyrwang** [comment]
thx! I found the location in the code where it sets 'bert' as default.
