### ISSUE TITLE
--ml-backend-url option changed and where should i put --ml-backend-name ?

### ISSUE THREAD

**Issue by miyamonz** [heartexlabs/label-studio-transformers#2]
The current label-studio start command in the docker-compose.yml contains these options.
https://github.com/heartexlabs/label-studio-transformers/blob/9450322/docker-compose.yml#L15-L16
```yml
      --ml-backend-url http://label-studio-ml-backend:9090
      --ml-backend-name my_model
```
but the current label-studio doesn't have them.

`label-studio start -h` and I found it changed to `--ml-backend`.
I fixed this and I could see localhost:8200.

but where should I put a model name?

**Comment by miyamonz** [comment]
https://github.com/heartexlabs/label-studio/pull/255/files#diff-95af22d4c88a84c480fc1c20efcf3ec1R157-R158

it seems that it changed by supporting multiple ml backends.
and the name seems to be generated by uuid.

so it doesn't matter that I don't specify ml name, it does?

**Comment by niklub** [comment]
Hi, @miyamonz ! Yes, the interface has been changed, so we need to fix this deployment too. Thanks reporting this.

**Comment by niklub** [comment]
Hi, @miyamonz ! The interface has been updated. Please check installation and usage in README

**Comment by miyamonz** [comment]
thanks! I'll try it.
