### ISSUE TITLE
Can't make predictions: ML backend returns an error (ner.py)

### ISSUE THREAD

**Issue by Ecclesiast** [heartexlabs/label-studio-transformers#6]
Steps to reproduce:

1. Using docker to start up the server `docker-compose up --build`
2. Used import sample with three tasks `[{"text":"To have faith is to trust yourself to the water"},{"text":"To have faith is to trust yourself to the water"},{"text":"To have faith is to trust yourself to the water"}]`
3. Completed two tasks and trained huggingface transformer from ner.py.
4. Go to UI for third task prediction.
5. No prediction.

**Requirements:**
torch==1.5.0
transformers==2.4.1
tensorboardX==1.9
label-studio>=0.7.0

Full logs are here:
```
[2020-08-31 15:07:49,882] [ERROR] [label_studio.utils.models::make_predictions::528] Can't make predictions: ML backend returns an error: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```
Can you help me please with this issue?

**Comment by makseq** [comment]
@Ecclesiast Hi! Can you switch to release/0.7.5 (pip install label-studio==0.7.5rc0) and check the error there. 
It has more detailed logs for ML.

**Comment by makseq** [comment]
@Ecclesiast Sorry.. you are using a docker... you need to build 0.7.5 docker. 

What labeling config do you use?

**Comment by Ecclesiast** [comment]
Hi. Thank you for your help. I have updated label-studio to 0.7.5 in docker and now everything is working. Thanks!
