### ISSUE TITLE
label-studio requirement incorrect, also getting old

### ISSUE THREAD

**Issue by RevelaAutumn** [heartexlabs/label-studio-transformers#7]
The README example does not work as is -- `label-studio==1.0.0` does not provide the command `label-studio-ml`, and does not expose `LabelStudioMLBase`.  

It works OK with `label-studio==0.7`, but that's not what's specified in requirements.txt.

(NB that it also doesn't work with the current head of `label-studios-ml-backend`).

**Comment by niklub** [comment]
Hi, @RevelaAutumn ! Thanks reporting this. Can you please drop here an issue log of what's happening after connecting to [label-studio-ml-backend](https://github.com/heartexlabs/label-studio-ml-backend) ? (Indeed, the ML backend has been moved to a separate repo, but API hasn't changed)

**Comment by RevelaAutumn** [comment]
Hi @niklub , I never even get there, the issue log would be
```
 ~ label-studio-ml
pyenv: label-studio-ml: command not found   
```

Really I'm just saying that the requirements.txt shouldn't permit label-studio v1.0 until the transformers project has been tested with it!

**Comment by niklub** [comment]
Hi, @RevelaAutumn 
Label Studio 1.0. compatibility issues have been fixed in the latest master, please try it out and reopen the issue In case you get any problem
